### ISSUE TITLE
Segmentation Support

### ISSUE THREAD

**Issue by amitbcp** [rggs/Wav_IIC#1]
I was trying to experiment with IIC, and was looking for a more new build with Python3 & pytorch >=1.0
I cam across the repository. Thanks for open sourcing it.
Could you please help me to understand , does the implementation support segmentation and pytorch>1.0 ?

**Comment by rggs** [comment]
This is actually a copied, modified version of a different project:
https://github.com/xu-ji/IIC
I'd refer you to that, however, when I first started working on it neither Python3 nor pytorch>1.0 were working, so you may have to do some leg work to get it to work.
